program: baselines/il/run_bc_from_scratch.py
method: grid
name: norm_ablation2
metric:
  goal: minimize
  name: eval/loss
parameters:
  experiments:
    values:
      - {
          # ExperimentConfig
          batch_size: 512,
          epochs: 500,
          lr: 0.0005,
          sample_per_epoch: 438763,
          # NetworkConfig
          network_dim: 128,
          network_num_layers: 2,
          act_func: "tanh",
          dropout: 0.0,
          norm: "LN",
          # HeadConfig
          head_dim: 128,
          head_num_layers: 2,
          action_dim: 3,
          n_components: 10,
          time_dim: 91,
          clip_values: -20.0,
          # Args
          model_name : "late_fusion",
          loss_name: "gmm"
      }
