parameters:
  datasetInitOptions: RandomN
  observationRadius: 1000.0
  polylineReductionThreshold: 1.0
  rewardParams: reward_params
reward_params:
  distanceToExpertThreshold: 1.0
  distanceToGoalThreshold: 1.0
  rewardType: DistanceBased
sim_manager:
  auto_reset: true
  exec_mode: CUDA
  gpu_id: 0
  json_path: /home/aarav/nocturne_data/formatted_json_v2_no_tl_valid
  num_worlds: 5
