[build-system]
requires = ["poetry-core"]
build-backend = "madrona-py-build"
backend-path = ["external/madrona/py"]

[project]
name = "gpudrive"
version = "0.0.1"

[tool.madrona.packages.gpudrive]
ext-only = true
ext-out-dir = "build"

# This module includes the PPO implementation for the training demo
[tool.madrona.packages.gpudrive_learn]
path = "train_src/gpudrive_learn"

[tool.poetry.build]
script = "build.py"

[tool.poetry.scripts]
config = "config:main"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.2.1"
numpy = "1.23.3"
gymnasium = "^0.29.1"
stable-baselines3 = "^2.2.1"
pufferlib = "^0.7.2"
tqdm = "^4.66.2"
wandb = "^0.16.4"
pyyaml = "^6.0.1"
matplotlib = "^3.8.3"
seaborn = "^0.13.2"

[tool.poetry]
name = "gpudrive"
version = "0.1.0"
description = ""
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
readme = "README.md"
packages = [
    {include = "gpudrive.cpython-311-x86_64-linux-gnu.so", from = "build", to = "gpudrive"},
    {include = "gpudrive_learn", from = "train_src", to = "gpudrive_learn"},
]