name: Run C++ tests

on:
  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev libc++1
        
    - name: Setup Conda environment.
      uses: conda-incubator/setup-miniconda@v3
      with:
         activate-environment: gpudrive
         environment-file: environment.yml

    - name: Install dependencies and build the project with Poetry
      run: |
        poetry install
    - name: Run tests
      run: |
        pytest -v

    - name: Upload core dumps
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: core-dumps
        path: /home/runner/work/gpudrive/gpudrive/core_dumps/